### ISSUE TITLE
fix(ci): implement issue labeler

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/hwakabh.github.io#139]
## AsIs
Though we have labeler in current pipeline implementation for triaging PRs, this is only applicable for Pull Request, and we have to manually add labels when we newly raise issue from template.

## ToDo
- [x] added workflow steps with [`github/issue-labeler`](https://github.com/github/issue-labeler)
- [x] export its config as another file, where we would define regexp matches with title of issue

## (Optional) Acceptance
- [x] CI of Triaging issue will be invoked when we create issue
- [x] CI of Triaging issue will be invoked when we update issue
- [x] label will be automatically added as expected with configs
