### ISSUE TITLE
fix(ci): dependabot checks for GitHub Actions

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/hwakabh.github.io#142]
## AsIs
Though we configured dependabot version check for GitHub Actions, it seems not working properly to detect target workflow files.
Meaning, we can only see the following files in Dependency graph in Insight tabs:
- `dependabot.yaml`
- `release.yaml`
- `semantic.yml`

Since they all are just for configuration files for GitHub builtin features, whereas the expected behaviors are to point the files under `./github/workflows/*`.

This seems because we have specified wrong value to key `directory`, where [document](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directory) says below:

> For GitHub Actions, you do not need to set the directory to /.github/workflows.
> Configuring the key to / automatically instructs Dependabot to search the /.github/workflows directory, as well as the action.yml / action.yaml file from the root directory.

## ToDo
- [x] fix value of `directory` with `/`
- [x] do adhoc checks in repository settings

## (Optional) Acceptance
- [x] confirm that our pipeline files are listed in target files of dependabot
- [x] adhoc testing will detect staled gh-action job images
